### PR TITLE
Nodejs/week3

### PR DESCRIPTION
**Pull request by cph-kiwi**
I have finished my nodejs/week3 homework. This is the warmup part.

### CODE REVIEW

**Review by Ekamba — CHANGES_REQUESTED** [review]
Hi @cph-kiwi, you have to clean up your commit by removing all files except index.js, .gitignore and package.json. The rest don't have anything to do here. And you don't need post request as your data is not going anywhere.

**Comment by cph-kiwi** [comment]
Thanks for reviewing this PR. However, I don't understand your comment. I followed the instructions exactly by copying over the entire warmup folder to my homework repo, so all these extra files came with it. I'd like to provide PRs in a form that is easy to review in the future. Can you give specific instructions about how to clean up my commit?
The post request was part of the homework requirements: https://github.com/HackYourFuture-CPH/node.js/tree/master/week3/homework-template

**Comment by Ekamba** [comment]
> Thanks for reviewing this PR. However, I don't understand your comment. I followed the instructions exactly by copying over the entire warmup folder to my homework repo, so all these extra files came with it. I'd like to provide PRs in a form that is easy to review in the future. Can you give specific instructions about how to clean up my commit?
> The post request was part of the homework requirements: https://github.com/HackYourFuture-CPH/node.js/tree/master/week3/homework-template

The repo you should copy the template for warm up from is this one: https://github.com/HackYourFuture-CPH/node.js/tree/master/week3/homework/warmup . And can see there is only three files inside `index.js, .gitignore and package.json`, you have 17 files files in your PR and except the three files I tell you those others files are not related to your warmup. Maybe you committed them by mistake, I hope you understand.

**Comment by cph-kiwi** [comment]
OK. Thanks.

**Pull request merged**
